<article class="day-desc"><h2>--- Day 10: Factory ---</h2><p>Just across the hall, you find a large factory. Fortunately, the Elves here have plenty of time to decorate. Unfortunately, it's because the factory machines are all offline, and none of the Elves can figure out the initialization procedure.</p>
<p>The Elves do have the manual for the machines, but the section detailing the initialization procedure was eaten by a <a href="https://en.wikipedia.org/wiki/Shiba_Inu">Shiba Inu</a>. All that remains of the manual are some indicator light diagrams, button wiring schematics, and <a href="3">joltage</a> requirements for each machine.</p>
<p>For example:</p>
<pre><code>[.##.] (3) (1,3) (2) (2,3) (0,2) (0,1) {3,5,4,7}
[...#.] (0,2,3,4) (2,3) (0,4) (0,1,2) (1,2,3,4) {7,5,12,7,2}
[.###.#] (0,1,2,3,4) (0,3,4) (0,1,2,4,5) (1,2) {10,11,11,5,10,5}
</code></pre>
<p>The manual describes one machine per line. Each line contains a single indicator light diagram in <code>[</code>square brackets<code>]</code>, one or more button wiring schematics in <code>(</code>parentheses<code>)</code>, and joltage requirements in <code>{</code>curly braces<code>}</code>.</p>
<p>To start a machine, its <em>indicator lights</em> must match those shown in the diagram, where <code>.</code> means <em>off</em> and <code>#</code> means <em>on</em>. The machine has the number of indicator lights shown, but its indicator lights are all <em>initially off</em>.</p>
<p>So, an indicator light diagram like <code>[.##.]</code> means that the machine has four indicator lights which are initially off and that the goal is to simultaneously configure the first light to be off, the second light to be on, the third to be on, and the fourth to be off.</p>
<p>You can <em>toggle</em> the state of indicator lights by pushing any of the listed <em>buttons</em>. Each button lists which indicator lights it toggles, where <code>0</code> means the first light, <code>1</code> means the second light, and so on. When you push a button, each listed indicator light either turns on (if it was off) or turns off (if it was on). You have to push each button an integer number of times; there's no such thing as "<span title="But only because these aren't A buttons.">0.5 presses</span>" (nor can you push a button a negative number of times).</p>
<p>So, a button wiring schematic like <code>(0,3,4)</code> means that each time you push that button, the first, fourth, and fifth indicator lights would all toggle between on and off. If the indicator lights were <code>[#.....]</code>, pushing the button would change them to be <code>[...##.]</code> instead.</p>
<p>Because none of the machines are running, the joltage requirements are irrelevant and can be safely ignored.</p>
<p>You can push each button as many times as you like. However, to save on time, you will need to determine the <em>fewest total presses</em> required to correctly configure all indicator lights for all machines in your list.</p>
<p>There are a few ways to correctly configure the first machine:</p>
<pre><code>[.##.] (3) (1,3) (2) (2,3) (0,2) (0,1) {3,5,4,7}</code></pre>
<ul>
<li>You could press the first three buttons once each, a total of <code>3</code> button presses.</li>
<li>You could press <code>(1,3)</code> once, <code>(2,3)</code> once, and <code>(0,1)</code> twice, a total of <code>4</code> button presses.</li>
<li>You could press all of the buttons except <code>(1,3)</code> once each, a total of <code>5</code> button presses.</li>
</ul>
<p>However, the fewest button presses required is <code><em>2</em></code>. One way to do this is by pressing the last two buttons (<code>(0,2)</code> and <code>(0,1)</code>) once each.</p>
<p>The second machine can be configured with as few as <code><em>3</em></code> button presses:</p>
<pre><code>[...#.] (0,2,3,4) (2,3) (0,4) (0,1,2) (1,2,3,4) {7,5,12,7,2}</code></pre>
<p>One way to achieve this is by pressing the last three buttons (<code>(0,4)</code>, <code>(0,1,2)</code>, and <code>(1,2,3,4)</code>) once each.</p>
<p>The third machine has a total of six indicator lights that need to be configured correctly:</p>
<pre><code>[.###.#] (0,1,2,3,4) (0,3,4) (0,1,2,4,5) (1,2) {10,11,11,5,10,5}</code></pre>
<p>The fewest presses required to correctly configure it is <code><em>2</em></code>; one way to do this is by pressing buttons <code>(0,3,4)</code> and <code>(0,1,2,4,5)</code> once each.</p>
<p>So, the fewest button presses required to correctly configure the indicator lights on all of the machines is <code>2</code> + <code>3</code> + <code>2</code> = <code><em>7</em></code>.</p>
<p>Analyze each machine's indicator light diagram and button wiring schematics. <em>What is the fewest button presses required to correctly configure the indicator lights on all of the machines?</em></p>
</article>

In [9]:
from dotenv import load_dotenv

load_dotenv()

True

In [10]:
from aocd import get_data

puzzle_input = get_data(day=10, year=2025)
print(f"{len(puzzle_input.splitlines())=}")

len(puzzle_input.splitlines())=174


In [11]:
sample_input = """[.##.] (3) (1,3) (2) (2,3) (0,2) (0,1) {3,5,4,7}
[...#.] (0,2,3,4) (2,3) (0,4) (0,1,2) (1,2,3,4) {7,5,12,7,2}
[.###.#] (0,1,2,3,4) (0,3,4) (0,1,2,4,5) (1,2) {10,11,11,5,10,5}"""
sample_input

'[.##.] (3) (1,3) (2) (2,3) (0,2) (0,1) {3,5,4,7}\n[...#.] (0,2,3,4) (2,3) (0,4) (0,1,2) (1,2,3,4) {7,5,12,7,2}\n[.###.#] (0,1,2,3,4) (0,3,4) (0,1,2,4,5) (1,2) {10,11,11,5,10,5}'

In [12]:
def diagram_to_mask(diagram: str) -> int:
    """Convert a diagram string to a bitmask integer."""
    return int("".join("1" if c == "#" else "0" for c in diagram), 2)


f"{diagram_to_mask('.##.'):04b}"

'0110'

In [13]:
def button_to_mask(button: tuple[int, ...], width: int) -> int:
    return int(
        "".join("1" if i in button else "0" for i in range(width)),
        2,
    )


f"{button_to_mask((0, 1, 3), 4):04b}"

'1101'

In [14]:
from dataclasses import dataclass
from typing import Self


@dataclass(frozen=True, slots=True)
class Machine:
    target_mask: int
    buttons_masks: tuple[int, ...]
    width: int
    joltage_requirements: tuple[int, ...]

    @classmethod
    def from_string(cls, s: str) -> Self:
        diagram_part, *buttons_parts, joltage_part = s.split()
        diagram = diagram_part.strip("[]")
        width = len(diagram)
        target_mask = diagram_to_mask(diagram)
        buttons_masks = tuple(
            button_to_mask(
                tuple(int(i) for i in part.strip("()").split(",")),
                width,
            )
            for part in buttons_parts
        )
        joltage_requirements = tuple(
            int(i) for i in joltage_part.strip("{}").split(",")
        )
        return cls(
            target_mask=target_mask,
            buttons_masks=buttons_masks,
            width=width,
            joltage_requirements=joltage_requirements,
        )


sample_machine = Machine.from_string(sample_input.splitlines()[0])
sample_machine

Machine(target_mask=6, buttons_masks=(1, 5, 2, 3, 10, 12), width=4, joltage_requirements=(3, 5, 4, 7))

In [ ]:
import numpy as np
from numpy.typing import NDArray


def build_matrix(button_masks: tuple[int, ...], width: int) -> NDArray[np.int_]:
    """Returns a (len(button_masks), width) matrix."""
    matrix = np.zeros((len(button_masks), width), dtype=int)
    for i, mask in enumerate(button_masks):
        for j in range(width):
            if (mask >> (width - 1 - j)) & 1:
                matrix[i, j] = 1
    return matrix


build_matrix(sample_machine.buttons_masks, sample_machine.width)

array([[0, 0, 0, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 0]])

In [ ]:
def build_target_vector(target_mask: int, width: int) -> NDArray[np.int_]:
    """Returns a (width,) vector."""
    vector = np.zeros((width,), dtype=int)
    for j in range(width):
        if (target_mask >> (width - 1 - j)) & 1:
            vector[j] = 1
    return vector


build_target_vector(sample_machine.target_mask, sample_machine.width)

array([0, 1, 1, 0])

In [24]:
A = build_matrix(sample_machine.buttons_masks, sample_machine.width)
b = build_target_vector(sample_machine.target_mask, sample_machine.width)

print("Matrix A (buttons × lights):")
print(A)
print("\nTarget vector b:")
print(b)

Matrix A (buttons × lights):
[[0 0 0 1]
 [0 1 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [1 0 1 0]
 [1 1 0 0]]

Target vector b:
[0 1 1 0]


In [26]:
print(A.shape)
print(b.shape)

(6, 4)
(4,)


In [29]:
# Create augmented matrix [A | b]
augmented = np.column_stack([A.T, b]).copy()  # copy() to avoid modifying original
print("Augmented matrix [A | b]:")
print(augmented)
print(f"Shape: {augmented.shape}")  # Should be (6 rows, 5 columns)

Augmented matrix [A | b]:
[[0 0 0 0 1 1 0]
 [0 1 0 0 0 1 1]
 [0 0 1 1 1 0 1]
 [1 1 0 1 0 0 0]]
Shape: (4, 7)


In [ ]:
# Make a working copy
aug = augmented.copy()
num_rows, num_cols = aug.shape
num_vars = num_cols - 1  # Last column is b

pivot_row = 0
pivot_cols = []

for col in range(num_vars):
    # Find a row with a 1 in this column, starting from pivot_row
    for row in range(pivot_row, num_rows):
        if aug[row, col] == 1:
            # Swap this row with the pivot_row
            if row != pivot_row:
                aug[[pivot_row, row]] = aug[[row, pivot_row]]

            # Record this as a pivot column
            pivot_cols.append(col)

            # Eliminate: XOR this row with all other rows that have a 1 in this column
            for other_row in range(num_rows):
                if other_row != pivot_row and aug[other_row, col] == 1:
                    # XOR the entire row (mod 2 addition)
                    aug[other_row] = (aug[other_row] + aug[pivot_row]) % 2

            # Move to next pivot position
            pivot_row += 1
            break
    else:
        # No pivot in this column (it's a free variable)
        continue

print("Reduced matrix:")
print(aug)
print(f"\nPivot columns: {pivot_cols}")

Reduced matrix:
[[1 0 0 1 0 1 1]
 [0 1 0 0 0 1 1]
 [0 0 1 1 0 1 1]
 [0 0 0 0 1 1 0]]

Pivot columns: [0, 1, 2, 4]


In [ ]:
# Check for inconsistency (row of all zeros except last column)
for row in range(num_rows):
    if np.all(aug[row, :-1] == 0) and aug[row, -1] == 1:
        print("No solution exists!")
        x0 = None
    else:
        # Extract one solution x0
        x0 = np.zeros(num_vars, dtype=int)
        for i, col in enumerate(pivot_cols):
            # Read off the solution from the augmented column
            x0[col] = aug[i, -1]

        print("One solution x0:")
        print(x0)
        print(f"Button presses: {np.where(x0 == 1)[0]}")
        print(f"Total presses: {np.sum(x0)}")

# Identify free variables (columns without pivots)
free_cols = [c for c in range(num_vars) if c not in pivot_cols]
print(f"\nFree variables (buttons): {free_cols}")

One solution x0:
[1 1 1 0 0 0]
Button presses: [0 1 2]
Total presses: 3
One solution x0:
[1 1 1 0 0 0]
Button presses: [0 1 2]
Total presses: 3
One solution x0:
[1 1 1 0 0 0]
Button presses: [0 1 2]
Total presses: 3
One solution x0:
[1 1 1 0 0 0]
Button presses: [0 1 2]
Total presses: 3

Free variables (buttons): [3, 5]


In [ ]:
# Build nullspace basis
nullspace_basis = []

for free_col in free_cols:
    # Create a basis vector with 1 at the free variable position
    null_vec = np.zeros(num_vars, dtype=int)
    null_vec[free_col] = 1

    # For each pivot row, if it has a 1 in this free column,
    # we must also set the corresponding pivot variable to 1
    for i, pivot_col in enumerate(pivot_cols):
        if aug[i, free_col] == 1:
            null_vec[pivot_col] = 1

    nullspace_basis.append(null_vec)
    print(f"Nullspace vector for free button {free_col}: {null_vec}")

print(f"\nNullspace basis ({len(nullspace_basis)} vectors):")
for i, vec in enumerate(nullspace_basis):
    print(f"  {i}: {vec}")

Nullspace vector for free button 3: [1 0 1 1 0 0]
Nullspace vector for free button 5: [1 1 1 0 1 1]

Nullspace basis (2 vectors):
  0: [1 0 1 1 0 0]
  1: [1 1 1 0 1 1]
